-- Flyway Migration: create_password_reset_tokens
-- Auto-generated diff by MigrationGenerator (Prisma-like)
-- Timestamp: 20260731155124

create table password_reset_tokens (id integer generated by default as identity, created_at timestamp(6) not null, expires_at timestamp(6) not null, token varchar(100) not null, used boolean not null, user_id integer not null, primary key (id));
create index idx_prt_user_id on password_reset_tokens (user_id);
alter table if exists password_reset_tokens drop constraint if exists idx_prt_token;
alter table if exists password_reset_tokens add constraint idx_prt_token unique (token);
alter table if exists password_reset_tokens add constraint FKk3ndxg5xp6v7wd4gjyusp15gq foreign key (user_id) references users;
